-- Migration: Create employees table
-- Description: Creates the employees table with all employee information fields

CREATE TABLE IF NOT EXISTS `employees` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `employee_id` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) DEFAULT NULL,
  `email` VARCHAR(100) DEFAULT NULL,
  `phone` VARCHAR(20) DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `gender` ENUM('male', 'female', 'other') DEFAULT NULL,
  `dob` DATE DEFAULT NULL,
  `photo` VARCHAR(255) DEFAULT NULL,
  `position` VARCHAR(100) DEFAULT NULL,
  `qualification` VARCHAR(200) DEFAULT NULL,
  `work_experience` VARCHAR(200) DEFAULT NULL,
  `hire_date` DATE DEFAULT NULL,
  `date_of_leaving` DATE DEFAULT NULL,
  `employment_status` ENUM('full-time', 'part-time', 'contract', 'intern', 'terminated') NOT NULL DEFAULT 'full-time',
  `contract_type` VARCHAR(20) DEFAULT NULL,
  `work_shift` VARCHAR(50) DEFAULT NULL,
  `current_location` VARCHAR(100) DEFAULT NULL,
  `reporting_to` INT(11) DEFAULT NULL,
  `emergency_contact` VARCHAR(20) DEFAULT NULL,
  `emergency_contact_relation` VARCHAR(50) DEFAULT NULL,
  `marital_status` VARCHAR(20) DEFAULT NULL,
  `father_name` VARCHAR(100) DEFAULT NULL,
  `mother_name` VARCHAR(100) DEFAULT NULL,
  `local_address` TEXT DEFAULT NULL,
  `permanent_address` TEXT DEFAULT NULL,
  `bank_account_name` VARCHAR(100) DEFAULT NULL,
  `bank_account_no` VARCHAR(50) DEFAULT NULL,
  `bank_name` VARCHAR(100) DEFAULT NULL,
  `bank_branch` VARCHAR(100) DEFAULT NULL,
  `ifsc_code` VARCHAR(20) DEFAULT NULL,
  `basic_salary` DECIMAL(10, 2) DEFAULT NULL,
  `facebook` VARCHAR(255) DEFAULT NULL,
  `twitter` VARCHAR(255) DEFAULT NULL,
  `linkedin` VARCHAR(255) DEFAULT NULL,
  `instagram` VARCHAR(255) DEFAULT NULL,
  `resume` VARCHAR(255) DEFAULT NULL,
  `joining_letter` VARCHAR(255) DEFAULT NULL,
  `other_documents` TEXT DEFAULT NULL,
  `notes` TEXT DEFAULT NULL,
  `is_superadmin` TINYINT(1) NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_by` INT(11) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `employees_employee_id_key` (`employee_id`),
  KEY `employees_email_index` (`email`),
  KEY `employees_reporting_to_index` (`reporting_to`),
  KEY `employees_created_by_index` (`created_by`),
  KEY `employees_is_active_index` (`is_active`),
  KEY `employees_is_superadmin_index` (`is_superadmin`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
